<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 04 Aug 2014 03:36:20 +0000
 */


$conf['title'] = 'CAF e.V. Mitglieder-Wiki';
$conf['lang'] = 'de';
$conf['license'] = '0';
$conf['dmode'] = 0775;
$conf['fmode'] = 0664;
$conf['toptoclevel'] = '2';
$conf['maxtoclevel'] = '5';
$conf['useacl'] = 1;
$conf['authtype'] = 'authowncloud';
$conf['defaultgroup'] = 'camerata';
$conf['superuser'] = 'admin';
$conf['manager'] = '@camerata';
$conf['disableactions'] = 'register';
$conf['remote'] = 1;
$conf['remoteuser'] = '@camerata,@admin';
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['updatecheck'] = 0;
$conf['plugin']['authorlist']['automatic'] = 1;
$conf['plugin']['authorlist']['displaystyle'] = 'fullname (loginname)';
$conf['plugin']['authorlist']['tooltip'] = 'loginname';
$conf['plugin']['authorlist']['showheading'] = 1;
$conf['plugin']['authorlist']['heading'] = 'Authoren';
$conf['plugin']['authorlist']['intro'] = '<p><b>Bislang mitwirkende Authoren:</b></p>';
$conf['plugin']['authorlist']['showcreator'] = 'below';
$conf['plugin']['authorlist']['creatortext'] = '<p>Erste Fassung von <i>%CREATOR%</i> am %DATE%.</p>';
$conf['plugin']['authorlist']['linkto'] = 'userhomepage';
$conf['plugin']['authowncloud']['pathtoowncloud'] = '/is/htdocs/wp1173590_IDUP6S1903/admin/owncloud7';
$conf['plugin']['authowncloud']['disableoclogout'] = 1;
$conf['plugin']['discussion']['allowguests'] = 0;
$conf['plugin']['discussion']['showguests'] = 0;
$conf['plugin']['discussion']['linkemail'] = 1;
$conf['plugin']['discussion']['newestfirst'] = 1;
$conf['plugin']['discussion']['visibilityButton'] = 1;
$conf['plugin']['dw2pdf']['usecache'] = 0;
$conf['plugin']['owncloud']['pathtoowncloud'] = '/is/htdocs/wp1173590_IDUP6S1903/members/owncloud';
$conf['plugin']['owncloud']['owncloudurl'] = 'http://membercloud.cafev.de';

// end auto-generated content
