<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sun, 16 Nov 2014 15:48:08 +0000
 */

$conf['title'] = 'CAF e.V. Administrations-Wiki';
$conf['lang'] = 'de';
$conf['license'] = '0';
$conf['dmode'] = 0770;
$conf['fmode'] = 0660;
$conf['useacl'] = 1;
$conf['authtype'] = 'authowncloud';
$conf['defaultgroup'] = 'camerata';
$conf['superuser'] = '@admin';
$conf['manager'] = '@camerata';
$conf['disableactions'] = 'register';
$conf['auth_security_timeout'] = 0;
$conf['remote'] = 1;
$conf['remoteuser'] = '@camerata,@admin';
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['updatecheck'] = 0;
$conf['plugin']['authorlist']['automatic'] = 1;
$conf['plugin']['authorlist']['displaystyle'] = 'fullname (loginname)';
$conf['plugin']['authorlist']['tooltip'] = 'loginname';
$conf['plugin']['authorlist']['showheading'] = 1;
$conf['plugin']['authorlist']['linkto'] = 'email';
$conf['plugin']['dw2pdf']['usecache'] = 0;
$conf['plugin']['authowncloud']['pathtoowncloud'] = '/var/www/localhost/htdocs/owncloud7';
$conf['plugin']['authowncloud']['disableoclogout'] = 1;
$conf['plugin']['owncloud']['pathtoowncloud'] = '/var/www/localhost/htdocs/owncloud7';
$conf['plugin']['owncloud']['owncloudurl'] = 'https://fritz.claus-justus-heine.info:8888/owncloud7';
$conf['plugin']['ckgedit']['preload_ckeditorjs'] = 1;
$conf['plugin']['odt2dw']['parserMimeTypeAuthorized'] = 'application/vnd.oasis.opendocument.text
application/octetstream';

// end auto-generated content
